---
- name: configurar nginx
  hosts: tag_Name_RPS
  become: True
  roles:
    - nginx
    
- name: desplegar página de bienvenida
  hosts: tag_Name_RPS
  become: True
  tasks:
    - name: copiar página de bienvenida
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html


